import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { updateMe, getLogbookStats } from '../api';
import { useToast } from '../context/ToastContext';
import { jsPDF } from 'jspdf';

function generateCertificate(user, stats) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const cx = W / 2;

  // Background
  doc.setFillColor(250, 250, 255);
  doc.rect(0, 0, W, H, 'F');

  // Emerald border (double)
  doc.setDrawColor(5, 150, 105);
  doc.setLineWidth(4);
  doc.rect(8, 8, W - 16, H - 16);
  doc.setLineWidth(1);
  doc.rect(12, 12, W - 24, H - 24);

  // Corner accents
  const accent = () => { doc.setFillColor(5, 150, 105); };
  accent(); doc.rect(8, 8, 18, 2, 'F');
  accent(); doc.rect(8, 8, 2, 18, 'F');
  accent(); doc.rect(W - 26, 8, 18, 2, 'F');
  accent(); doc.rect(W - 10, 8, 2, 18, 'F');
  accent(); doc.rect(8, H - 10, 18, 2, 'F');
  accent(); doc.rect(8, H - 26, 2, 18, 'F');
  accent(); doc.rect(W - 26, H - 10, 18, 2, 'F');
  accent(); doc.rect(W - 10, H - 26, 2, 18, 'F');

  // Header label
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(5, 150, 105);
  doc.text('OJT BUDDY  ·  CERTIFICATE OF COMPLETION', cx, 28, { align: 'center', charSpace: 2 });

  // Divider line
  doc.setDrawColor(5, 150, 105);
  doc.setLineWidth(0.4);
  doc.line(cx - 60, 32, cx + 60, 32);

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(36);
  doc.setTextColor(15, 23, 42);
  doc.text('Certificate of Completion', cx, 58, { align: 'center' });

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text('This is to certify that', cx, 72, { align: 'center' });

  // Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(5, 150, 105);
  doc.text(user.name || 'Student Name', cx, 90, { align: 'center' });

  // Name underline
  doc.setDrawColor(5, 150, 105);
  doc.setLineWidth(0.5);
  const nameW = doc.getTextWidth(user.name || 'Student Name');
  doc.line(cx - nameW / 2, 93, cx + nameW / 2, 93);

  // Body text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);
  const totalHours = parseFloat(stats?.total_hours || 0).toFixed(1);
  const totalDays = stats?.total_days || 0;
  const required = user.required_hours || 486;
  doc.text(
    `has successfully completed the On-the-Job Training (OJT) program`,
    cx, 106, { align: 'center' }
  );
  doc.text(
    `with a total of ${totalHours} hours rendered over ${totalDays} days`,
    cx, 114, { align: 'center' }
  );
  if (user.course) {
    doc.text(`under the ${user.course} program.`, cx, 122, { align: 'center' });
  }

  // Stats boxes
  const boxY = 134;
  const boxes = [
    { label: 'Hours Rendered', value: `${totalHours}h` },
    { label: 'Days Completed', value: `${totalDays}` },
    { label: 'Required Hours', value: `${required}h` },
    { label: 'Batch', value: user.batch || '—' },
  ];
  const boxW = 44; const boxH = 18; const gap = 8;
  const totalW = boxes.length * boxW + (boxes.length - 1) * gap;
  let bx = cx - totalW / 2;
  boxes.forEach(b => {
    doc.setFillColor(236, 253, 245);
    doc.setDrawColor(5, 150, 105);
    doc.setLineWidth(0.5);
    doc.roundedRect(bx, boxY, boxW, boxH, 3, 3, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(5, 150, 105);
    doc.text(b.value, bx + boxW / 2, boxY + 8, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(b.label.toUpperCase(), bx + boxW / 2, boxY + 14, { align: 'center', charSpace: 0.5 });
    bx += boxW + gap;
  });

  // Date issued
  const issued = new Date().toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`Issued on ${issued}  ·  Generated by OJT Buddy`, cx, H - 18, { align: 'center' });

  doc.save(`OJT_Certificate_${(user.name || 'Student').replace(/\s+/g, '_')}.pdf`);
}

export default function Profile() {
  const { user, setUser } = useAuth();
  const [form, setForm] = useState({
    name: user?.name || '',
    course: user?.course || '',
    batch: user?.batch || '',
    ojt_start_date: user?.ojt_start_date?.slice(0, 10) || '',
    required_hours: user?.required_hours || 486,
  });
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState('');
  const toast = useToast();

  const set = (f) => (e) => setForm({ ...form, [f]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true); setSuccess(false); setError('');
    try {
      const res = await updateMe(form);
      setUser(res.data);
      setSuccess(true);
      toast('Profile updated!');
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      const msg = err.response?.data?.error || 'Save failed';
      setError(msg);
      toast(msg, 'error');
    } finally {
      setSaving(false);
    }
  };

  const handleCertificate = async () => {
    setGenerating(true);
    try {
      const res = await getLogbookStats();
      generateCertificate(user, res.data);
      toast('Certificate downloaded!');
    } catch {
      toast('Failed to generate certificate', 'error');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1>Profile & Settings</h1>
          <p className="page-subtitle">Update your OJT information</p>
        </div>
        <button className="btn-primary" onClick={handleCertificate} disabled={generating}>
          {generating ? 'Generating...' : '🎓 Download Certificate'}
        </button>
      </div>

      <div className="profile-layout">
        <div className="profile-avatar-card card">
          <div className="profile-avatar-big">{user?.name?.[0]?.toUpperCase()}</div>
          <div className="profile-name">{user?.name}</div>
          <div className="profile-email">{user?.email}</div>
          <div className="profile-meta">
            <div className="profile-meta-item">
              <span className="profile-meta-label">Course</span>
              <span className="profile-meta-value">{user?.course || '—'}</span>
            </div>
            <div className="profile-meta-item">
              <span className="profile-meta-label">Batch</span>
              <span className="profile-meta-value">{user?.batch || '—'}</span>
            </div>
            <div className="profile-meta-item">
              <span className="profile-meta-label">Required Hours</span>
              <span className="profile-meta-value">{user?.required_hours}h</span>
            </div>
            <div className="profile-meta-item">
              <span className="profile-meta-label">OJT Start</span>
              <span className="profile-meta-value">
                {user?.ojt_start_date ? new Date(user.ojt_start_date).toLocaleDateString('en-PH', { month: 'long', day: 'numeric', year: 'numeric' }) : '—'}
              </span>
            </div>
          </div>
        </div>

        <div className="card">
          <h2 className="card-title">Edit Information</h2>
          <form onSubmit={handleSubmit} className="profile-form">
            {error && <div className="form-error">{error}</div>}
            {success && <div className="form-success">Changes saved!</div>}
            <div className="form-group">
              <label>Full Name</label>
              <input value={form.name} onChange={set('name')} required />
            </div>
            <div className="form-group">
              <label>Course</label>
              <input value={form.course} onChange={set('course')} />
            </div>
            <div className="form-row">
              <div className="form-group">
                <label>Batch</label>
                <input value={form.batch} onChange={set('batch')} placeholder="e.g. 2025A" />
              </div>
              <div className="form-group">
                <label>Required Hours</label>
                <input type="number" value={form.required_hours} onChange={set('required_hours')} min={1} />
              </div>
            </div>
            <div className="form-group">
              <label>OJT Start Date</label>
              <input type="date" value={form.ojt_start_date} onChange={set('ojt_start_date')} />
            </div>
            <button type="submit" className="btn-primary" disabled={saving}>
              {saving ? 'Saving...' : 'Save Changes'}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
